version: '3.7'

services:
  sicrediapp:
    image: fernandocauper/sicrediapp:latest
    restart: on-failure
    depends_on:
      - sicredimysql
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sicredimysql:3306/sicrediapp?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root



  sicredimysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sicrediapp
    ports:
      - 3306:3306
